# Original source from https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
blueprint:
  name: Motion-activated Light with sun condition, and override.
  description: Turn on a light when motion is detected and sun is set, and override.
  domain: automation
  source_url: https://github.com/zLucPlayZ/home-assistant-blueprints/blob/master/motion_light_sunset.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    ref_light_target:
      name: Reference Light
      selector:
        entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    sunset_offset:
      name: Offset to turn on lights
      description: Define offset to sunset
      default: 60
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    sunrise_offset:
      name: Offset to turn off lights
      description: Define offset to sunrise
      default: 45
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

variables:
  ref_light_target: !input ref_light_target

condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: !input ref_light_target
      state: "off"
    - condition: template   
      value_template: "{{ states[ref_light_target].context.user_id == none }}"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    entity_id: !input ref_light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    entity_id: !input ref_light_target
